# Catpuccin Colors
import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  #"~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

# Basic Window Config
[window]
    padding.x = 12
    padding.y = 12
    decorations = "Full"

# Default font
[font]
    normal.family = "GeistMono Nerd Font"
    size = 16.0

# Cursor settings
[cursor.style]
    shape = "Block"
    blinking = "Always"

# Vim cursor settings -- this is not erroring, but is not working
[cursor.vi_mode_style]
    shape = "Block"
    blinking = "Always"

# Mouse settings
[mouse]
    hide_when_typing = true

# Needed for colors ands stuff
[env]
    TERM = "xterm-256color"
